<?php

return [
    0  => 'Nhiệm vụ đầu tiên',
    1  => 'Nhiệm vụ tập luyện',
    2  => 'Nhiệm vụ tìm thức ăn',
    3  => 'Tìm kiếm sao băng',
    4  => 'Nhiệm vụ khó khăn',
    5  => 'Nhiệm vụ gia tăng sức mạnh',
    6  => 'Nhiệm vụ trò chuyện',
    7  => 'Nhiệm vụ giải cứu',
    8  => 'Nhiệm vụ ân nhân xuất sắc',
    9  => 'Nhiệm vụ tiên học lễ',
    10 => 'Nhiệm vụ học phí',
    11 => 'Nhiệm vụ kết giao',
    12 => 'Nhiệm vụ xin phép',
    13 => 'Nhiệm vụ gia nhập bang hội',
    14 => 'Nhiệm vụ bang hội lần 1',
    15 => 'Nhiệm vụ bang hội lần 2',
    16 => 'Tiêu diệt quái vật',
    17 => 'Nhiệm vụ giúp đỡ Cui',
    18 => 'Nhiệm vụ bất khả thi',
    19 => 'Nhiệm vụ chạm trán đệ tử',
    20 => 'Nhiệm vụ Tiểu Đội Sát Thủ',
    21 => 'Nhiệm vụ chạm trán Fide đại ca',
    22 => 'Nhiệm vụ chạm trán Rôbốt sát thủ lần 1',
    23 => 'Nhiệm vụ chạm trán Rôbốt sát thủ lần 2',
    24 => 'Nhiệm vụ giải cứu thị trấn Ginder',
    25 => 'Tiêu Diệt Xên Đi Mấy Em',
    26 => 'Tiêu Diệt Xên Đi Mấy Em',
    27 => 'Kết Bạn Nhìu Niềm Vui',
    28 => 'Săn Xên Bên Võ Đài Nhé',
    29 => 'Tìm Đường Tới Cold',
    30 => 'Tiêu Diệt Bọn Người Máy Doraemon!',
    31 => 'Nhiệm Vụ Bất Khả Thi',
    32 => 'Đang cập nhật!',
];
